name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Memicu workflow saat push ke branch "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js dengan versi yang cocok
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Sesuaikan dengan versi yang Anda butuhkan

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project using Vite
      - name: Build project
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token $VERCEL_TOKEN
